//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SensorAnalogico.App.Assets {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SensorAnalogico.App.Assets.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Embarked.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string ButtonBack {
            get {
                return ResourceManager.GetString("ButtonBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analog Input Configuration Parameters.
        /// </summary>
        public static string LabelAnalogInputConfigurationParameters {
            get {
                return ResourceManager.GetString("LabelAnalogInputConfigurationParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barometric Pressure.
        /// </summary>
        public static string LabelBarometricPressure {
            get {
                return ResourceManager.GetString("LabelBarometricPressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Command.
        /// </summary>
        public static string LabelButtonChangeCommand {
            get {
                return ResourceManager.GetString("LabelButtonChangeCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Configuration.
        /// </summary>
        public static string LabelButtonChangeConfiguration {
            get {
                return ResourceManager.GetString("LabelButtonChangeConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Input.
        /// </summary>
        public static string LabelButtonGetInput {
            get {
                return ResourceManager.GetString("LabelButtonGetInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Command.
        /// </summary>
        public static string LabelButtonSaveCommand {
            get {
                return ResourceManager.GetString("LabelButtonSaveCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Configuration.
        /// </summary>
        public static string LabelButtonSaveConfiguration {
            get {
                return ResourceManager.GetString("LabelButtonSaveConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibration.
        /// </summary>
        public static string LabelCalibration {
            get {
                return ResourceManager.GetString("LabelCalibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibration 1:.
        /// </summary>
        public static string LabelCalibration1 {
            get {
                return ResourceManager.GetString("LabelCalibration1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibration 2:.
        /// </summary>
        public static string LabelCalibration2 {
            get {
                return ResourceManager.GetString("LabelCalibration2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibration 3:.
        /// </summary>
        public static string LabelCalibration3 {
            get {
                return ResourceManager.GetString("LabelCalibration3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibration 4:.
        /// </summary>
        public static string LabelCalibration4 {
            get {
                return ResourceManager.GetString("LabelCalibration4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibration 5:.
        /// </summary>
        public static string LabelCalibration5 {
            get {
                return ResourceManager.GetString("LabelCalibration5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibration 6.
        /// </summary>
        public static string LabelCalibration6 {
            get {
                return ResourceManager.GetString("LabelCalibration6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibration Points.
        /// </summary>
        public static string LabelCalibrationPoints {
            get {
                return ResourceManager.GetString("LabelCalibrationPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command.
        /// </summary>
        public static string LabelCommand {
            get {
                return ResourceManager.GetString("LabelCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command Type Parameters.
        /// </summary>
        public static string LabelCommandTypeParameters {
            get {
                return ResourceManager.GetString("LabelCommandTypeParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component Id.
        /// </summary>
        public static string LabelComponentId {
            get {
                return ResourceManager.GetString("LabelComponentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component Identity.
        /// </summary>
        public static string LabelComponentIdentity {
            get {
                return ResourceManager.GetString("LabelComponentIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        public static string LabelConfiguration {
            get {
                return ResourceManager.GetString("LabelConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration Parameters.
        /// </summary>
        public static string LabelConfigurationParameters {
            get {
                return ResourceManager.GetString("LabelConfigurationParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Status.
        /// </summary>
        public static string LabelGeneralStatus {
            get {
                return ResourceManager.GetString("LabelGeneralStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microcontroller ID.
        /// </summary>
        public static string LabelMicrocontrollerId {
            get {
                return ResourceManager.GetString("LabelMicrocontrollerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moisture.
        /// </summary>
        public static string LabelMoisture {
            get {
                return ResourceManager.GetString("LabelMoisture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string LabelStatus {
            get {
                return ResourceManager.GetString("LabelStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Command.
        /// </summary>
        public static string LabelStatusCommand {
            get {
                return ResourceManager.GetString("LabelStatusCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Configuration.
        /// </summary>
        public static string LabelStatusConfiguration {
            get {
                return ResourceManager.GetString("LabelStatusConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature.
        /// </summary>
        public static string LabelTemperature {
            get {
                return ResourceManager.GetString("LabelTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Time:.
        /// </summary>
        public static string LabelUpdateTime {
            get {
                return ResourceManager.GetString("LabelUpdateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string LabelValue {
            get {
                return ResourceManager.GetString("LabelValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value 1:.
        /// </summary>
        public static string LabelValue1 {
            get {
                return ResourceManager.GetString("LabelValue1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value 2:.
        /// </summary>
        public static string LabelValue2 {
            get {
                return ResourceManager.GetString("LabelValue2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value 3:.
        /// </summary>
        public static string LabelValue3 {
            get {
                return ResourceManager.GetString("LabelValue3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value 4:.
        /// </summary>
        public static string LabelValue4 {
            get {
                return ResourceManager.GetString("LabelValue4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value 5:.
        /// </summary>
        public static string LabelValue5 {
            get {
                return ResourceManager.GetString("LabelValue5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value 6.
        /// </summary>
        public static string LabelValue6 {
            get {
                return ResourceManager.GetString("LabelValue6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analog Input Configuration.
        /// </summary>
        public static string TitleAnalogInputConfigurationScreen {
            get {
                return ResourceManager.GetString("TitleAnalogInputConfigurationScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analog Input.
        /// </summary>
        public static string TitleAnalogInputScreen {
            get {
                return ResourceManager.GetString("TitleAnalogInputScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Climate Sensors.
        /// </summary>
        public static string TitleClimateSensorScreen {
            get {
                return ResourceManager.GetString("TitleClimateSensorScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component Screen.
        /// </summary>
        public static string TitleComponentScreen {
            get {
                return ResourceManager.GetString("TitleComponentScreen", resourceCulture);
            }
        }
    }
}
